name: lux-glasses
channels:
dependencies:
   - python=3.9
   - pytorch::pytorch
   - cudatoolkit=11.3
   - matplotlib
   - numpy
   - scikit-learn
   - pandas
   - pip
   - seaborn
   - scipy
   - pip:
     - tqdm
